### ISSUE TITLE
ArgumentError: Package RandomNumbers does not have Requires in its dependencies:

### ISSUE THREAD

**Issue by varnerlab** [sunoru/RandomNumbers.jl#54] opened 2019-02-14 21:31 UTC
Tests fail for RandomNumbers on OSX (10.14.3) on Julia 1.10.

Procedure:
1) ] up 
2) test RandomNumbers

Results:
Testing RandomNumbers
 Resolving package versions...
    Status `/var/folders/26/dyl9dp2157z1g3sck948l6s40000gn/T/tmpK4hg52/Manifest.toml`
  [e6cf234a] RandomNumbers v1.1.0
  [2a0f44e3] Base64  [`@stdlib/Base64`]
  [ade2ca70] Dates  [`@stdlib/Dates`]
  [8ba89e20] Distributed  [`@stdlib/Distributed`]
  [b77e0a4c] InteractiveUtils  [`@stdlib/InteractiveUtils`]
  [76f85450] LibGit2  [`@stdlib/LibGit2`]
  [56ddb016] Logging  [`@stdlib/Logging`]
  [d6f4376e] Markdown  [`@stdlib/Markdown`]
  [44cfe95a] Pkg  [`@stdlib/Pkg`]
  [de0858da] Printf  [`@stdlib/Printf`]
  [3fa0cd96] REPL  [`@stdlib/REPL`]
  [9a3f8284] Random  [`@stdlib/Random`]
  [ea8e919c] SHA  [`@stdlib/SHA`]
  [9e88b42a] Serialization  [`@stdlib/Serialization`]
  [6462fe0b] Sockets  [`@stdlib/Sockets`]
  [8dfed614] Test  [`@stdlib/Test`]
  [cf7118a7] UUIDs  [`@stdlib/UUIDs`]
  [4ec0a83e] Unicode  [`@stdlib/Unicode`]
ERROR: LoadError: ArgumentError: Package RandomNumbers does not have Requires in its dependencies:
- If you have RandomNumbers checked out for development and have
  added Requires as a dependency but haven't updated your primary
  environment's manifest file, try `Pkg.resolve()`.
- Otherwise you may need to report an issue with RandomNumbers
Stacktrace:
 [1] require(::Module, ::Symbol) at ./loading.jl:836
 [2] include at ./boot.jl:326 [inlined]
 [3] include_relative(::Module, ::String) at ./loading.jl:1038
 [4] include(::Module, ::String) at ./sysimg.jl:29
 [5] top-level scope at none:2
 [6] eval at ./boot.jl:328 [inlined]
 [7] eval(::Expr) at ./client.jl:404
 [8] top-level scope at ./none:3
in expression starting at /Users/jeffreyvarner/.julia/packages/RandomNumbers/aomjt/src/RandomNumbers.jl:32
ERROR: LoadError: LoadError: Failed to precompile RandomNumbers [e6cf234a-135c-5ec9-84dd-332b85af5143] to /Users/jeffreyvarner/.julia/compiled/v1.1/RandomNumbers/pgCpR.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1197
 [3] _require(::Base.PkgId) at ./loading.jl:960
 [4] require(::Base.PkgId) at ./loading.jl:858
 [5] require(::Module, ::Symbol) at ./loading.jl:853
 [6] include at ./boot.jl:326 [inlined]
 [7] include_relative(::Module, ::String) at ./loading.jl:1038
 [8] include at ./sysimg.jl:29 [inlined]
 [9] include(::String) at /Users/jeffreyvarner/.julia/packages/RandomNumbers/aomjt/test/runtests.jl:7
 [10] top-level scope at none:0
 [11] eval(::Module, ::Any) at ./boot.jl:328
 [12] top-level scope at /Users/jeffreyvarner/.julia/packages/RandomNumbers/aomjt/test/runtests.jl:7
 [13] include at ./boot.jl:326 [inlined]
 [14] include_relative(::Module, ::String) at ./loading.jl:1038
 [15] include(::Module, ::String) at ./sysimg.jl:29
 [16] include(::String) at ./client.jl:403
 [17] top-level scope at none:0
in expression starting at /Users/jeffreyvarner/.julia/packages/RandomNumbers/aomjt/test/common.jl:1
in expression starting at /Users/jeffreyvarner/.julia/packages/RandomNumbers/aomjt/test/runtests.jl:1
ERROR: Package RandomNumbers errored during testing

I noticed a commit a few hours ago (on 2/14/19 around 2:30 EST USA) to fix this issue, was fine *before* the commit. Broken after?

**Comment by varnerlab** [comment] 2019-02-14 21:59
*Update:* 

I added *directly* from the Git repo, and seems to be fine/fixed:

Procedure (at the Julia REPL):
1) ]
2) add https://github.com/sunoru/RandomNumbers.jl.git
3) test RandomNumbers
4) All tests passed

**Comment by sunoru** [comment] 2019-02-14 22:48
Thanks for telling me this!

It seems this issue is caused by that Requires.jl isn't installed automatically when being updated. I'm looking into it.

**Comment by GregPlowman** [comment] 2019-02-14 22:53
Actually just `using RandomNumbers` causes an error for me:

```
Julia-1.1.0> using RandomNumbers
[ Info: Precompiling RandomNumbers [e6cf234a-135c-5ec9-84dd-332b85af5143]
ERROR: LoadError: ArgumentError: Package RandomNumbers does not have Requires in its dependencies:
- If you have RandomNumbers checked out for development and have
  added Requires as a dependency but haven't updated your primary
  environment's manifest file, try `Pkg.resolve()`.
- Otherwise you may need to report an issue with RandomNumbers
Stacktrace:
 [1] require(::Module, ::Symbol) at .\loading.jl:836
 [2] include at .\boot.jl:326 [inlined]
 [3] include_relative(::Module, ::String) at .\loading.jl:1038
 [4] include(::Module, ::String) at .\sysimg.jl:29
 [5] top-level scope at none:2
 [6] eval at .\boot.jl:328 [inlined]
 [7] eval(::Expr) at .\client.jl:404
 [8] top-level scope at .\none:3
in expression starting at D:\Users\plowman\.julia\packages\RandomNumbers\aomjt\src\RandomNumbers.jl:32
ERROR: Failed to precompile RandomNumbers [e6cf234a-135c-5ec9-84dd-332b85af5143] to D:\Users\plowman\.julia\compiled\v1.1\RandomNumbers\pgCpR.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1197
 [3] _require(::Base.PkgId) at .\loading.jl:960
 [4] require(::Base.PkgId) at .\loading.jl:858
 [5] require(::Module, ::Symbol) at .\loading.jl:853
```

**Comment by sunoru** [comment] 2019-02-14 22:56
I see... I should have also added the dependency in REQUIRE file (but not only in Project.toml). I'm sorry to be not familiar with this.

**Comment by ChrisRackauckas** [comment] 2019-02-14 23:00
It's because it needs to be in the REQUIRE file for METADATA to work: https://github.com/sunoru/RandomNumbers.jl/pull/55

**Comment by sunoru** [comment] 2019-02-14 23:02
Yes, I see. It's my fault for forgetting this...

**Comment by ChrisRackauckas** [comment] 2019-02-14 23:03
It's all good. It's a quick fix and we're good to go.

**Comment by sunoru** [comment] 2019-02-14 23:04
Will be fixed when this is merged: https://github.com/JuliaLang/METADATA.jl/pull/21443

**Closed** 2019-02-15 07:10 UTC
